/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, FoodMenu as PrismaFoodMenu } from "@prisma/client";

export class FoodMenuServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.FoodMenuCountArgs, "select">): Promise<number> {
    return this.prisma.foodMenu.count(args);
  }

  async foodMenus(
    args: Prisma.FoodMenuFindManyArgs
  ): Promise<PrismaFoodMenu[]> {
    return this.prisma.foodMenu.findMany(args);
  }
  async foodMenu(
    args: Prisma.FoodMenuFindUniqueArgs
  ): Promise<PrismaFoodMenu | null> {
    return this.prisma.foodMenu.findUnique(args);
  }
  async createFoodMenu(
    args: Prisma.FoodMenuCreateArgs
  ): Promise<PrismaFoodMenu> {
    return this.prisma.foodMenu.create(args);
  }
  async updateFoodMenu(
    args: Prisma.FoodMenuUpdateArgs
  ): Promise<PrismaFoodMenu> {
    return this.prisma.foodMenu.update(args);
  }
  async deleteFoodMenu(
    args: Prisma.FoodMenuDeleteArgs
  ): Promise<PrismaFoodMenu> {
    return this.prisma.foodMenu.delete(args);
  }
}
