/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Waiter } from "./Waiter";
import { WaiterCountArgs } from "./WaiterCountArgs";
import { WaiterFindManyArgs } from "./WaiterFindManyArgs";
import { WaiterFindUniqueArgs } from "./WaiterFindUniqueArgs";
import { CreateWaiterArgs } from "./CreateWaiterArgs";
import { UpdateWaiterArgs } from "./UpdateWaiterArgs";
import { DeleteWaiterArgs } from "./DeleteWaiterArgs";
import { TablesFindManyArgs } from "../../tables/base/TablesFindManyArgs";
import { Tables } from "../../tables/base/Tables";
import { WaiterService } from "../waiter.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Waiter)
export class WaiterResolverBase {
  constructor(
    protected readonly service: WaiterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "read",
    possession: "any",
  })
  async _waitersMeta(
    @graphql.Args() args: WaiterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Waiter])
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "read",
    possession: "any",
  })
  async waiters(@graphql.Args() args: WaiterFindManyArgs): Promise<Waiter[]> {
    return this.service.waiters(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Waiter, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "read",
    possession: "own",
  })
  async waiter(
    @graphql.Args() args: WaiterFindUniqueArgs
  ): Promise<Waiter | null> {
    const result = await this.service.waiter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Waiter)
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "create",
    possession: "any",
  })
  async createWaiter(@graphql.Args() args: CreateWaiterArgs): Promise<Waiter> {
    return await this.service.createWaiter({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Waiter)
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "update",
    possession: "any",
  })
  async updateWaiter(
    @graphql.Args() args: UpdateWaiterArgs
  ): Promise<Waiter | null> {
    try {
      return await this.service.updateWaiter({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Waiter)
  @nestAccessControl.UseRoles({
    resource: "Waiter",
    action: "delete",
    possession: "any",
  })
  async deleteWaiter(
    @graphql.Args() args: DeleteWaiterArgs
  ): Promise<Waiter | null> {
    try {
      return await this.service.deleteWaiter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Tables], { name: "tablesItems" })
  @nestAccessControl.UseRoles({
    resource: "Tables",
    action: "read",
    possession: "any",
  })
  async findTablesItems(
    @graphql.Parent() parent: Waiter,
    @graphql.Args() args: TablesFindManyArgs
  ): Promise<Tables[]> {
    const results = await this.service.findTablesItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
